version: '3'
services:
    build-sys:
        image: monius/build-system-ubuntu:personal
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        cap_add:
            - NET_ADMIN
            - SYS_ADMIN
            - SYS_PTRACE
        command: ". /run/entrypoint.sh"


