version: '3'
services:
    build-sys:
        image: monius/build-system-ubuntu:personal
        cap_add:
            - NET_ADMIN
            - SYS_ADMIN
        network_mode: host
        devices:
            - "/dev/net/tun:/dev/net/tun"


