name: Build GOOGLE-BBR V2
on:
  push:
    branches: 
      - main
      - v2alpha
  pull_request:
    branches: 
      - main
      - v2alpha
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '30 6 * * 1'
    
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: true
        default: 'true'

env:
  REPO_URL: https://github.com/google/bbr
  REPO_BRANCH: v2alpha
  REPO_NAME: google-bbr
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: .config
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_WETRANSFER: false
  UPLOAD_RELEASE: false
  LOCALVERSION: ""
  GCE_PKG_DIR: ""
  GCE_INSTALL_DIR: ""
  GCE_BUILD_DIR: ""
  KERNEL_PKG: ""
  MAKE_OPTS: ""

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: init
        run: |
          sudo sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install $(curl -fsSL git.io/depends-ubuntu-2004)
          sudo -E apt-get -qq install kernel-package tmux
          sudo -E apt-get -qq build-dep linux
          sudo mkdir -p /bbr
          sudo chown $USER:$GROUPS /bbr

      - name: Clone source code
        working-directory: /bbr
        run: |
          df -hT $PWD
          git clone $REPO_URL -b $REPO_BRANCH $REPO_NAME
          ln -sf /bbr/$REPO_NAME $GITHUB_WORKSPACE/$REPO_NAME

      - name: set env and config
        working-directory: /bbr
        run: |
          cd $REPO_NAME
          echo ${PWD}
          echo "BRANCH=`git rev-parse --abbrev-ref HEAD | sed s/-/+/g` " >> $GITHUB_ENV
          echo "SHA1=`git rev-parse --short HEAD` " >> $GITHUB_ENV
          echo "LOCALVERSION=+${BRANCH}+${SHA1}+GCE " >> $GITHUB_ENV
          echo "GCE_PKG_DIR=${PWD}/gce/${LOCALVERSION}/pkg " >> $GITHUB_ENV
          echo "GCE_INSTALL_DIR=${PWD}/gce/${LOCALVERSION}/install " >> $GITHUB_ENV
          echo "GCE_BUILD_DIR=${PWD}/gce/${LOCALVERSION}/build " >> $GITHUB_ENV
          echo "KERNEL_PKG=kernel-${LOCALVERSION}.tar.gz2 " >> $GITHUB_ENV
          echo "MAKE_OPTS="-j`nproc` \
                    LOCALVERSION=${LOCALVERSION} \
                    EXTRAVERSION='' \
                    INSTALL_PATH=${GCE_INSTALL_DIR}/boot \
                    INSTALL_MOD_PATH=${GCE_INSTALL_DIR}" " >> $GITHUB_ENV
          echo "cleaning..."
          mkdir -p ${GCE_BUILD_DIR}
          mkdir -p ${GCE_INSTALL_DIR}/boot
          mkdir -p ${GCE_PKG_DIR}
          echo "copying config.gce to .config ..."
          cp config.gce .config
          
      - name: Disable DEBUG_INFO and DEBUG_INFO
        working-directory: /bbr
        run:
          echo $MAKE_OPTS
