name: Build GOOGLE-BBR V2 on openwrt bcm2711
on:
  push:
    branches: 
      - main
      - v2alpha

  schedule:
    - cron: '30 6 * * 1'
      
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: true
        default: 'true'

env:
  CONFIG_FILE_SOURCE: https://downloads.openwrt.org/releases/21.02.0-rc2/targets/bcm27xx/bcm2711/config.buildinfo
  REPO_URL: https://github.com/openwrt/openwrt
  REPO_BRANCH: master
  REPO_NAME: openwrt
  WORK_DIR: /openwrt
  FEEDS_CONF: feeds.conf.default
  UPLOAD_PKG_DIR: true
  UPLOAD_FIRMWARE: true
  UPLOAD_WETRANSFER: true
  UPLOAD_RELEASE: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          ref: 'main'

      - name: free space
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php* android*
          sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc

      - name: init
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install $(curl -fsSL git.io/bbrv2-ubuntu-2004)
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean
          sudo mkdir -p /release/upload
          sudo chown -R $USER:$GROUPS /release

      - name: Clone source code
        run: |
          git clone --depth 1 -b $REPO_BRANCH $REPO_URL $REPO_NAME
          sudo ln -sf $(pwd)/$REPO_NAME $WORK_DIR

      - name: Load feeds && configuration
        working-directory: ${{ env.WORK_DIR }}
        run: |
          curl -L $CONFIG_FILE_SOURCE -o .config
          ./scripts/feeds update -a && ./scripts/feeds install -a

      - name: Download package
        working-directory: ${{ env.WORK_DIR }}
        id: package
        run: |
          make defconfig
          make download -j8
          find dl -size -1024c -exec rm -f {} \;

      - name: Compile the firmware
        working-directory: ${{ env.WORK_DIR }}
        id: compile
        run: |
          echo -e "$(nproc) thread compile"
          make -j$(nproc) || make -j1 || make -j1 V=s
          echo "::set-output name=status::success"

      - name: Keep config and firmware
        working-directory: ${{ env.WORK_DIR }}
        id: show
        run: |
          mv .config /release/upload
          cd bin/targets/*/*
          rm -rf packages
          mv ./* /release/upload


      - name: List the firmware
        working-directory: ${{ env.WORK_DIR }}
        id: list
        run: |
          mv ./bin /release
          cd /release
          tree -L 3

      - name: Generate tag
        working-directory: ${{ env.WORK_DIR }}
        id: tag
        if: steps.compile.outputs.status == 'success' && env.UPLOAD_RELEASE == 'true' && !cancelled()
        run: |
          echo "::set-output name=release_name::openwrt_rpi_$(date +'%Y%m%d%H%M')"
          touch release.txt
          echo "::set-output name=status::success"
          
      - name: Upload packages
        uses: actions/upload-artifact@main
        if: steps.compile.outputs.status == 'success' && steps.tag.outputs.status == 'success' && env.UPLOAD_PKG_DIR == 'true'
        with:
          name: ${{ steps.tag.outputs.release_name }}
          path: /release/upload

      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 1
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS }}

      - name: Remove old Releases
        uses: dev-drprasad/delete-older-releases@v0.1.0
        if: env.UPLOAD_RELEASE == 'true' && !cancelled()
        with:
          keep_latest: 1
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS }}