name: Build QvTj-6.x - macos

on:
  push:
    branches: 
      - main
      - v2alpha
  pull_request:
    branches: 
      - main
      - v2alpha
  schedule:
    - cron: '30 6 * * 1'
      
  repository_dispatch:
  workflow_dispatch:
    inputs:
      release:
        description: 'Release the plugin'
        required: true
        default: 'false'

env:
  REPO_URL: https://github.com/Qv2ray/QvPlugin-Trojan-Go
  REPO_BRANCH: dev
  REPO_NAME: QvTj
  VERSION: ''

jobs:
  build:
    strategy:
      matrix:
        qt_version: [6.1.0]
        platform: [macos-latest]
      fail-fast: false
        
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          ref: 'main'

      - name: init
        run: |
          brew install tree
          sudo mkdir -p /opt/QvTj /opt/Release/upload
          sudo chown $USER:$GROUPS /opt/QvTj
          sudo chown -R $USER:$GROUPS /opt/Release

      - name: Clone source code
        working-directory: /opt/QvTj
        id: code
        run: |
          df -hT $PWD
          git clone -b $REPO_BRANCH $REPO_URL $REPO_NAME
          ln -sf /opt/QvTj/$REPO_NAME $GITHUB_WORKSPACE/$REPO_NAME
          cd $GITHUB_WORKSPACE/$REPO_NAME && git submodule update --init
          # echo "VERSION=$(set -- *.hpp; echo "$1" | grep -Eo "v[0-9].[0-9].[0-9]")" >> $GITHUB_ENV
          echo ::set-output name=VERSION::$(set -- *.hpp; echo "$1" | grep -Eo "v[0-9].[0-9].[0-9]")
          echo ::set-output name=SHA::$(git rev-parse --short HEAD)

      - name: Install Python 3.8 version
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'

      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: QtCache-${{ matrix.platform }}-${{ matrix.qt_version }}

      - name: Installing Qt - ${{ matrix.arch }}
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ matrix.qt_version }}
          arch: ${{ matrix.qtarch }}
          cached: ${{ steps.cache-qt.outputs.cache-hit }}

      - name: macOS - ${{ matrix.qt_version }} - Generate Dependencies and Build
        working-directory: /opt/QvTj/${{ env.REPO_NAME }}
        shell: bash
        if: matrix.platform == 'macos-latest'
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DQVPLUGIN_USE_QT6=ON
          cmake --build . --parallel $(sysctl -n hw.logicalcpu)
          mv $(set -- *.txt; echo "$1") /opt/Release/upload/lib${{ env.REPO_NAME }}.so

      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 1.0.0

      - name: macOS - ${{ matrix.qt_version }} - Uploading Artifact
        if: matrix.platform == 'macos-latest'
        uses: actions/upload-artifact@master
        with:
          name: ${{ env.REPO_NAME }}-${{ steps.code.outputs.SHA }}.macOS.Qt${{ matrix.qt_version }}.so
          path: /opt/Release/upload/lib${{ env.REPO_NAME }}.so

      - name: macOS - ${{ matrix.qt_version }} - Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        if: github.event.inputs.release == 'true' && matrix.platform == 'macos-latest'
        with:
          repo_token: ${{ secrets.ACTIONS }}
          file: /opt/Release/upload/lib${{ env.REPO_NAME }}.so
          asset_name: ${{ env.REPO_NAME }}.${{ steps.code.outputs.VERSION }}.macOS.Qt6.so
          tag: ${{ steps.previoustag.outputs.tag }}
          overwrite: true

      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 1
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS }}